[package]
name = "ps2keyboard"
version = "0.1.0"
authors = ["bjoernQ <bjoern.quentin@mobile-j.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp32c3-hal = "0.10.0"
esp-println = { version = "0.5.0", features = [ "esp32c3", "uart" ] }
esp-backtrace = { version = "0.7.0", features = [ "esp32c3", "print-uart", "panic-handler" ] }
pc-keyboard = "0.7.0"
critical-section = "1.1.1"
