[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]

[env]
# Use clean build after changing ESP_LOGLEVEL
ESP_LOGLEVEL="DEBUG"